### ISSUE TITLE
Can't Break Mekanism Cables

### ISSUE THREAD

**Issue by Flimsy-Fox** [mrihtar/Treecapitator#1]
Whenever I have Treecapitator Updated enabled, I can't seem to break Mekanism Basic Universal Cables. I am playing on Space Astronomy 2, in addition to Optifine and this mod. I have the latest corresponding 1.10.2 version installed, and am using Forge version 12.18.3.2511.

Here is the portion of the log that occurs when I try to left-click:
`[15:20:12] [Server thread/ERROR] [FML]: Index: 11 Listeners:
[15:20:12] [Server thread/ERROR] [FML]: 0: HIGHEST
[15:20:12] [Server thread/ERROR] [FML]: 1: ASM: com.mjr.spaceAstronomyTweaks.MainEventHandler@3187b559 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 2: ASM: com.oitsjustjose.tinkers_addons.modifiers.ModAutoRepair@78923f9b onUpdate(Lnet/minecraftforge/event/entity/player/PlayerEvent;)V
[15:20:12] [Server thread/ERROR] [FML]: 3: NORMAL
[15:20:12] [Server thread/ERROR] [FML]: 4: ASM: Block{enderio:blockConduitBundle} onBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 5: ASM: crazypants.enderio.item.darksteel.ItemDarkSteelAxe@789ecde2 onBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 6: ASM: crazypants.enderio.item.darksteel.ItemDarkSteelShears@4afa063 onBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 7: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@6053838 blockBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 8: ASM: flaxbeard.cyberware.common.item.ItemBrainUpgrade@15248324 handleMining(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 9: ASM: flaxbeard.cyberware.common.item.ItemHandUpgrade@6934ab62 handleMineSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 10: ASM: net.machinemuse.powersuits.event.HarvestEventHandler@71ff97d1 handleBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 11: ASM: bspkrs.treecapitator.forge.ForgeEventHandler@564f7c2b getPlayerBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 12: ASM: blusunrize.immersiveengineering.common.EventHandler@28ea1904 digSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 13: ASM: com.inventorypets.HarvestHandler@6fbc6d8a onPlayerBreaking(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 14: ASM: com.creativemd.littletiles.common.events.LittleEvent@7af392e4 speedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 15: ASM: slimeknights.tconstruct.tools.TraitEvents@4aa1e9d8 mineSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 16: ASM: slimeknights.tconstruct.library.tools.DualToolHarvestUtils@5f63fc3c offhandBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[15:20:12] [Server thread/ERROR] [FML]: 17: ASM: mob_grinding_utils.events.ChickenFuseEvent@55dc7295 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[15:20:12] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:484) ~[BlockMultipartContainer.class:?]
at bspkrs.util.ModulusBlockID.<init>(ModulusBlockID.java:27) ~[ModulusBlockID.class:?]
at bspkrs.util.ModulusBlockID.<init>(ModulusBlockID.java:32) ~[ModulusBlockID.class:?]
at bspkrs.treecapitator.forge.ForgeEventHandler.getPlayerBreakSpeed(ForgeEventHandler.java:50) ~[ForgeEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1001_ForgeEventHandler_getPlayerBreakSpeed_BreakSpeed.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:172) ~[ForgeEventFactory.class:?]
at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:859) ~[zs.class:?]
at mcmultipart.multipart.Multipart.getStrength(Multipart.java:235) ~[Multipart.class:?]
at mcmultipart.multipart.MultipartContainer.getHardness(MultipartContainer.java:358) ~[MultipartContainer.class:?]
at mcmultipart.block.BlockMultipartContainer.func_180647_a(BlockMultipartContainer.java:191) ~[BlockMultipartContainer.class:?]
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:395) ~[art$a.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:205) ~[lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more`

**Comment by Flimsy-Fox** [comment]
I have now isolated the issue only using Mekanism, Treecapitator Updated, and all required mods, using the same versions. The crash log is as follows:
https://pastebin.com/KEQ4AczC

**Comment by Flimsy-Fox** [comment]
I see this thread hasn't gotten any further; should I post this to Mekanism too, as that might also be part of the problem?
